### ISSUE TITLE
Doesn't work without global rimraf install

### ISSUE THREAD

**Issue by azz0r** [BTplc/js-framework-benchmarking-tool#4]
package.json is missing [rimraf](https://www.npmjs.com/package/rimraf)

> [0] > ngrt-performance@1.2.9 vue-build /Users/azz0r/Sites/js-framework-benchmarking-tool
> [0] > rimraf src/client-vue/dist       && webpack --config _build/client-vue/webpack.conf.js --progress --colors
> [0]
> [0] sh: rimraf: command not found
> [5] npm
> [5]  ERR!
> [5]  Darwin 16.0.0

**Comment by radswiat** [comment]
It should be in now: "rimraf": "^2.5.4"

thanks!
